name: all-execute

on:
  push:
    branches:
    - develop

jobs:
  deploy-stg:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: all-execute
      run: |
        ./test.sh