name: deploy prd

on:
  push:
    branches:
    - main

jobs:
  deploy-prd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: deploy prd
      run: |
        echo "deploy prd"