name: deploy stg

on:
  pull_request:
    branches:
      - staging
    types:
      - closed

jobs:
  deploy-stg:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
    - name: deploy stg ready
      run: |
        echo "deploy stg ready"

    - name: deploy stg process
      run: |
        echo "deploy stg process"