name: deploy prd

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy-prd:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
    - name: deploy prd ready
      run: |
        echo "deploy prd ready"

    - name: deploy prd process
      run: |
        echo "deploy prd process"