name: deploy stg

on:
  push:
    branches:
    - staging

jobs:
  production-lambda-function-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: deploy stg
      run: |
        echo "deploy stg"