name: Dev workflow

on:
  workflow_run:
    # git-secrets はワークフロー実行一覧で個別に確認できるようにしたいので、あえて個別に分ける
    workflows:
      - Run git-secrets
    types:
      - completed

jobs:
  eslint:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/eslint.yaml
  prettier:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/prettier.yaml
  hadolint:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/hadolint.yaml
  build-ts:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/build-ts.yaml
