name: Development flow

on:
  push:

jobs:
  eslint:
    uses: ./.github/workflows/eslint.yaml
  hadolint:
    uses: ./.github/workflows/hadolint.yaml
  prettier:
    needs:
      - eslint
      - hadolint
    uses: ./.github/workflows/prettier.yaml
