name: Run git-secrets

on:
  workflow_call:

jobs:
  git-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: awslabs/git-secrets
      - name: Install git-secrets
        run: |
          pwd
          ls -l
          cd git-secrets
          make install
      - name: debug 1
        run: |
          pwd
          ls -l
      - uses: actions/checkout@v4
      - name: debug 2
        run: |
          pwd
          ls -l
      - name: Setting git-secrets
        run: |
          git secrets --install
          git secrets --register-aws
      - name: Scan repository
        run: |
          git secrets --scan
