name: Run git-secrets

on:
  workflow_call:

jobs:
  build-ts:
    runs-on: ubuntu-latest
    steps:
      - name: Install git-secrets
        run: |
          git clone https://github.com/awslabs/git-secrets /opt/git-secrets
          cd /opt/git-secrets
          make install
      - name: debug 1
        run: |
          pwd
          ls -l
      - uses: actions/checkout@v4
      - name: debug 2
        run: |
          pwd
          ls -l
      - name: Setting git-secrets
        run: |
          git secrets --install
          git secrets --register-aws
      - name: Scan repository
        run: |
          git secrets --scan
