name: Run git-secrets

on:
  workflow_call:

jobs:
  git-secrets:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: main
    steps:
      - uses: actions/checkout@v4
        with:
          repository: awslabs/git-secrets
          path: git-secrets
      - name: Install git-secrets
        working-directory: git-secrets
        run: sudo make install
      - uses: actions/checkout@v4
      - name: debug 2
        run: |
          pwd
          ls -l
      - name: Setting git-secrets
        run: |
          git secrets --install
          git secrets --register-aws
      - name: Scan repository
        run: |
          git secrets --scan
