name: Run git-secrets

on:
  workflow_call:

jobs:
  git-secrets:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: main
    steps:
      - name: Checkout awslabs/git-secrets
        uses: actions/checkout@v4
        with:
          repository: awslabs/git-secrets
          path: git-secrets
      - name: Install git-secrets
        working-directory: git-secrets
        run: sudo make install
      - name: Checkout base commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: main
      - name: Checkout pull request commit
        uses: actions/checkout@v4
        with:
          path: main
      - name: Display commit log
        run: git log ${{ github.event.before }}.. --format="%s %H"
      - name: Display commit log
        run: git log ${{ github.event.pull_request.base.sha }}.. --format="%s %H"
      - name: Setting git-secrets
        run: |
          git secrets --install
          git secrets --register-aws
      - name: Scan repository
        run: |
          git secrets --scan-history
