name: Lint Dockerfile with hadolint

on:
  workflow_call:
    inputs:
      git-ref:
        required: true
        type: string

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git-ref }}
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
