name: Release test

on: 
  pull_request:
    branches:
      - staging
      - main

jobs:
  release-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: do test
      run: |
        echo "test release"